services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: organize_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: organize
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - organize_network

networks:
  organize_network:
    driver: bridge
