@base_url = http://localhost:8000
@token = {{create_session.response.body.access_token}}

### 
# @name create_account
POST {{base_url}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456789"
}

### 
# @name create_session
POST {{base_url}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456789"
}

### 
# @name create_supplier
POST {{base_url}}/suppliers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Denis",
  "email": "denis@example.com",
  "phone": "47999999999",
  "city": "Jaraguá do Sul",
  "state": "SC",
  "address": "Rua do Comércio, 123"
}

### 
# @name create_product
POST {{base_url}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Product",
  "price": 100,
  "reference": "123456",
  "supplierId": "225225b3-e6ee-40f4-88de-dc41c0433337",
  "attachments": []
}

### 
# @name create_servant
POST {{base_url}}/servants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Corte",
  "productIds": [],
  "productsPrice": 10,
  "workForcePrice": 20,
  "profitPercent": 112
}

###
# @name fetch_all_servants
GET {{base_url}}/servants/all
Authorization: Bearer {{token}}

### 
# @name create_servant_products
POST {{base_url}}/servant-products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "servantId": "02e3d480-2e19-4f89-8a66-e0ab891b973a",
  "productId": "1cb59a07-4119-41c0-8631-603e6a532b98"
}