@base_url = http://localhost:8000
@token = {{create_session.response.body.access_token}}

### 
# @name create_account
POST {{base_url}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456789"
}

### 
# @name create_session
POST {{base_url}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456789"
}

### 
# @name create_supplier
POST {{base_url}}/suppliers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Eduardo Bertozi",
  "email": "eduardo@example.com",
  "phone": "47999999999",
  "city": "Barra Velha",
  "state": "SC",
  "address": "Rua do Comércio, 123"
}

###
# @name fetch_suppliers
GET {{base_url}}/suppliers/all?page=1
Authorization: Bearer {{token}}

###
# @name fetch_sales
GET {{base_url}}/sales/all?page=1
Authorization: Bearer {{token}}

###
# @name fetch_sales-by-id
GET {{base_url}}/sales/asdasdsa
Authorization: Bearer {{token}}

### 
# @name create_product
POST {{base_url}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Product",
  "price": 100,
  "reference": "123456",
  "supplierId": "cab5b590-e058-4af6-98a5-bb94a15df339",
  "stock": 10,
  "attachments": []
}

### 
# @name upload_product
PUT {{base_url}}/products/876e117c-b703-46fe-8a48-a4e945ad15b0
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Lâmina de barbear",
  "price": 0.5,
  "reference": "REF123",
  "attachments": [
    "fff153fe-1d04-432c-b67b-c362a6ce7517",
    "1b17abd3-41c6-452c-93ef-a93adf4c0f45",
    "c1da39f6-1892-403b-bc43-3e510ef5bff"
  ],
  "supplierId": "cab5b590-e058-4af6-98a5-bb94a15df339",
  "stock": 10
}

### 
# @name fetch_all_products
GET {{base_url}}/products/all
Content-Type: application/json
Authorization: Bearer {{token}}

### 
# @name create_servant
POST {{base_url}}/servants
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Limpeza Facial",
  "profitPercent": 48,
  "workForcePrice": 30,
  "price": 30.488,
  "productsPrice": 0.6,
  "products": [
    {
      "id": "a889a9ee-1f01-4599-9049-c68a3575e4db",
      "name": "Lâmina de barbear",
      "price": 0.5,
      "supplierId": "1a59a5d8-900c-4988-90ce-49db2b80d8cb",
      "reference": "REF123",
      "attachments": [],
      "createdAt": "2025-03-31T03:46:47.461Z"
    },
    {
      "id": "0cd33cae-b9ee-452a-b782-ded516dce053",
      "name": "Gola higiênica",
      "price": 0.1,
      "supplierId": "1a59a5d8-900c-4988-90ce-49db2b80d8cb",
      "reference": "REF123",
      "attachments": [],
      "createdAt": "2025-03-31T03:46:47.461Z"
    }
  ]
}

###
# @name fetch_all_servants
GET {{base_url}}/servants/all
Authorization: Bearer {{token}}

### 
# @name create_servant_products
POST {{base_url}}/servant-products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "servantId": "9897d94d-d0c4-4d96-a6d5-9abcc44bbeac",
  "productId": "225cb98e-c6bb-4398-9760-c6a19cb01c04"
}

###
# @name fetch_all_servant_products
GET {{base_url}}/servant-products/9897d94d-d0c4-4d96-a6d5-9abcc44bbeac
Authorization: Bearer {{token}}